### ISSUE TITLE
[RHPDS] - tutorial app initialization

### ISSUE THREAD

**Issue by VinayBhalerao** [RedHatWorkshops/dayinthelife-integration#267]
After successful full install of scripts on vanilla integreatly rhpds, the user click on `https://tutorial-web-app-webapp.apps.mountainview-37b1.openshiftworkshop.com/` to get started. The provisioning screens displays only 3 components. Below are screenshots for firefox and chrome

**Screenshot:**

**Firefox**
![red_hat_solution_explorer](https://user-images.githubusercontent.com/7827135/52834567-5376cb80-3097-11e9-9736-b426616c2f48.png)

**Chrome**

![red_hat_solution_explorer](https://user-images.githubusercontent.com/7827135/52834598-7a350200-3097-11e9-9ffa-4a48ab9e142a.png)

**Comment by maleck13** [comment]
@aidenkeating any thoughts

**Comment by aidenkeating** [comment]
@maleck13 There is a configuration file that allows you to specify which services should be provisioned. I think a file like this is being added as part of the DIL installer as, from what I remember, the other services that were provisioned by default weren't needed as part of DIL.

@VinayBhalerao What is the issue here? That only 3 services are being provisioned? Or that the provisioning never ends/something else?

**Comment by VinayBhalerao** [comment]
@aidenkeating Only 3 services are shown as provisioning. At the end, the provisioning is successful and can see all services in solution explorer like below.


![red_hat_solution_explorer](https://user-images.githubusercontent.com/7827135/52875992-94f48e80-310a-11e9-83fe-b598f76605f5.png)

**Expected results**
During provisioning, all services should be displayed.

**Comment by VinayBhalerao** [comment]
Looks good. Closing.
